environment:
  matrix:
  - JULIAVERSION: "julianightlies/bin/winnt/x86/julia-latest-win32.exe"
  - JULIAVERSION: "julianightlies/bin/winnt/x64/julia-latest-win64.exe"

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

install:
  - ps: (new-object net.webclient).DownloadFile(
              $("http://s3.amazonaws.com/"+$env:JULIAVERSION),
              "C:\projects\julia-binary.exe"
        )
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.clone(pwd(), \"Chemharp\"); Pkg.build(\"Chemharp\")"
  - C:\projects\julia\bin\julia -e "using BinDeps; BinDeps.debug(\"Chemharp\")"

test_script:
  - C:\projects\julia\bin\julia --check-bounds=yes -e "Pkg.test(\"Chemharp\")"
